Time-based benchmark
sfu-dis/pibench pull request #37
Opened 2021-07-23 15:27 UTC by chongchong721

I'm adding a time-based benchmark mode. Users can specify the time PiBench runs.
--mode command is for choosing the mode
--time for specifying the running time
--false_access for generating unrepeated keys(to emulate false read and update)

2021-07-23 17:13 UTC, dpsi commented on include/key_generator.hpp
> +     * @param becnhmark_mode decides pibench's running mode( by number of ops or by time)
typo

2021-07-23 18:37 UTC, dpsi requested changes

2021-07-24 11:47 UTC, chongchong721 commented on src/benchmark.cpp
> +       << (opt.bm_mode ? "\t# Operations: " : "\t# Running time: ") << (opt.bm_mode ? opt.num_ops : opt.time) << "\n"
This part is printing the benchmark option(before the benchmark starts). num_ops is only used in operation mode, specifying the total number of operations during the benchmark process. Maybe you mean printing the total number of operations done during the time-based benchmark? This needs adding some stats.

2021-10-01 02:54 UTC, wangtzh commented
Closed (cherrypicked by the other `time-based-bench` branch.

2021-10-01 02:54 UTC, closed without merging